/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.engine.processor@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:8c892a8f9fdf4c149d3132d4de31c03bd2bbcf29c8750d67e1ef64d4edb50f1c";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface ProcessRequest {
  input_json: string;
}

export interface ProcessResponse {
  output_json: string;
}

export type ProcessError = "rejected" | UnknownDomainError;
export type ProcessInvocationError = { readonly kind: "domain"; readonly error: ProcessError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ProcessResult = { readonly ok: true; readonly value: ProcessResponse } | { readonly ok: false; readonly error: ProcessInvocationError };
export function encodeProcessRequest(value: ProcessRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeProcessRequest(wire: string): ProcessRequest { return lensoContractRuntime.decodePortableJson<ProcessRequest>(wire); }
export function encodeProcessResponse(value: ProcessResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeProcessResponse(wire: string): ProcessResponse { return lensoContractRuntime.decodePortableJson<ProcessResponse>(wire); }
export function encodeProcessError(value: ProcessError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeProcessError(wire: string): ProcessError { return lensoContractRuntime.decodeDomainError<ProcessError>(wire, ["rejected"]); }


export interface ProcessorClient {
  process(request: ProcessRequest, context?: InvocationContext): Promise<ProcessResult>;
}

export interface ProcessorProvider {
  process(context: InvocationContext, request: ProcessRequest): Promise<ProcessResult>;
}

export const Processor: CapabilityContractReference<ProcessorClient, ProcessorProvider, DependencyInvoker> = { kind: "lenso.capability", ...bindProcessorDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "ProcessorClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["process"], stream_operations: [], event_operations: [] }, bindProvider: bindProcessorProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const PROCESSOR_CONTRACT = Processor;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindProcessorProvider(
  provider: ProcessorProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["process"],
      stream_operations: [],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "process": {
        let request: ProcessRequest;
        try {
          request = decodeProcessRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.process(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeProcessResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeProcessError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = ProcessorProvider;
export const bindProvider = bindProcessorProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindProcessorDependency(): CapabilityDependencyBinding<ProcessorClient, DependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["process"],
      stream_operations: [],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async process(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeProcessRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("process", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeProcessResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeProcessError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindProcessorDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
