// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.engine.processor@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:8c892a8f9fdf4c149d3132d4de31c03bd2bbcf29c8750d67e1ef64d4edb50f1c";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = false;
pub const PROCESSOR_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const PROCESSOR_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const PROCESSOR_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const PROCESSOR_CONTRACT: CapabilityReference<ProcessorClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_processor { () => { "{\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"process\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":false}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_processor_client {
    () => { "{\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_processor_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_processor_client {
    () => { "{\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.engine.processor@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const PROCESS_OPERATION: &str = "process";

pub use lenso_contract_runtime::{RawJson, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessRequest {
    #[serde(rename = "input_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub input_json: RawJson,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ProcessResponse {
    #[serde(rename = "output_json")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub output_json: RawJson,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProcessError {
    Rejected,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct Processor;
impl RequestCapability for Processor {
    type Request = ProcessRequest;
    type Response = ProcessResponse;
    type DomainError = ProcessError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PROCESS_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<ProcessorRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).process(context, request)
    }
}

impl serde::Serialize for ProcessError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Rejected => serializer.serialize_str("rejected"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ProcessError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "rejected" => Ok(Self::Rejected),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_process_request(value: &ProcessRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_request(wire: &str) -> Result<ProcessRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_response(value: &ProcessResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_response(wire: &str) -> Result<ProcessResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_process_error(value: &ProcessError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_process_error(wire: &str) -> Result<ProcessError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoProcessorProcessResult {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure>;
}
impl __LensoIntoProcessorProcessResult for Result<ProcessResponse, ProcessError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoProcessorProcessResult for Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> { self }
}
impl __LensoIntoProcessorProcessResult for Result<ProcessResponse, lenso_plugin_authoring::PluginError<ProcessError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoProcessorProcessResult for Result<ProcessResponse, ProcessorInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ProcessResponse, ProcessError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(ProcessorInvocationError::Domain(error)) => Ok(Err(error)),
            Err(ProcessorInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait ProcessorProvider: fmt::Debug + 'static {
    fn process(&self, context: InvocationContext, request: ProcessRequest) -> NativeRequestFuture<Processor>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_processor {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProcessor;
        impl $crate::ProcessorProvider for $plugin {
        fn process(&self, context: __LensoNativeSupportProcessor::InvocationContext, request: $crate::ProcessRequest) -> __LensoNativeSupportProcessor::NativeRequestFuture<$crate::Processor> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::process(&plugin, context, request).await;
                $crate::__LensoIntoProcessorProcessResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_processor {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProcessor;
        impl $crate::ProcessorProvider for $object {
        fn process(&self, context: __LensoNativeSupportProcessor::InvocationContext, request: $crate::ProcessRequest) -> __LensoNativeSupportProcessor::NativeRequestFuture<$crate::Processor> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::process(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoProcessorProcessResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_processor {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportProcessor;
        impl $crate::ProcessorProvider for $object {
        fn process(&self, context: __LensoNativeSupportProcessor::InvocationContext, request: $crate::ProcessRequest) -> __LensoNativeSupportProcessor::NativeRequestFuture<$crate::Processor> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::ProcessorProvider>::process(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct ProcessorRequestEndpoint { provider: Rc<dyn ProcessorProvider> }

#[derive(Debug)]
pub struct ProcessorEndpoint<P: ProcessorProvider> { provider: Rc<P>, request_endpoint: ProcessorRequestEndpoint }
impl<P: ProcessorProvider> ProcessorEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn ProcessorProvider> = provider.clone();
        Self { provider, request_endpoint: ProcessorRequestEndpoint { provider: request_provider } }
    }
}

impl<P: ProcessorProvider> NativeRequestEndpoint for ProcessorEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        PROCESS_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            PROCESS_OPERATION => {
                let Ok(request) = request.downcast::<ProcessRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).process(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_processor {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::ProcessorEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_processor {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_processor!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct ProcessorClient {
    process: NativeRequestHandle<Processor>,
}
impl ProcessorClient {
    pub fn new(handle: NativeRequestHandle<Processor>) -> Self {
        Self { process: handle }
    }

    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn process(&self, request: ProcessRequest) -> Result<ProcessResponse, ProcessorInvocationError> {
        self.process.invoke(PROCESS_OPERATION, request).await
            .map_err(ProcessorInvocationError::Runtime)?
            .map_err(ProcessorInvocationError::Domain)
    }

    pub async fn process_with_context(&self, context: InvocationContext, request: ProcessRequest) -> Result<ProcessResponse, ProcessorInvocationError> {
        self.process.invoke_with_context(PROCESS_OPERATION, context, request).await
            .map_err(ProcessorInvocationError::Runtime)?
            .map_err(ProcessorInvocationError::Domain)
    }
}

impl CapabilityClient for ProcessorClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            process: dependencies.one::<Processor>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for ProcessorClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    process: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<Processor>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProcessorInvocationError {
    Domain(ProcessError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct ProcessorGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> ProcessorGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[PROCESS_OPERATION], &[], &[])
            .map(|capability| Self { capability })
    }

    pub fn process(&self, request: &ProcessRequest) -> Result<ProcessResponse, lenso_guest_sdk::GuestError<ProcessError>> {
        self.capability.request(PROCESS_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct ProcessorJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for ProcessorJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[PROCESS_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }
    fn event_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            PROCESS_OPERATION => {
                let value = request.downcast_ref::<ProcessRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PROCESS_OPERATION => serde_json::from_value::<ProcessResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            PROCESS_OPERATION => serde_json::from_value::<ProcessError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_event(&self, operation: &str, _event: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            PROCESS_OPERATION => {
                let request = serde_json::from_value::<ProcessRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<Processor>()?;
                    match handle.invoke_with_context(PROCESS_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }

    fn publish_host_event(&self, _dependency: lenso_kernel::PluginEventDependencyHandle, operation: String, _event: serde_json::Value, _context: InvocationContext) -> futures::future::LocalBoxFuture<'static, Result<(), RuntimeFailure>> {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
