/* @generated by lenso-contract-codegen; do not edit. */
import * as lensoContractRuntime from "@lenso/contract-runtime";

export const CAPABILITY_ID = "lenso.terminal.command-provider@1";
export const DESCRIPTOR_VERSION = "1.0.0";
export const DESCRIPTOR_DIGEST = "sha256:66f8210cc8079012b8d8e6686e4853b5a4ed930e9a8275559691e4b63dd7a744";
export const PORTABLE = true;
export const CROSS_LANE_TRANSFER = false;

export type Int64 = lensoContractRuntime.Int64;
export type Uint64 = lensoContractRuntime.Uint64;
export type Bytes = lensoContractRuntime.Bytes;
export type Timestamp = lensoContractRuntime.Timestamp;
export type Duration = lensoContractRuntime.Duration;
export type OptionalValue<T> = lensoContractRuntime.OptionalValue<T>;
export type InvocationContext = lensoContractRuntime.InvocationContext;
export type RuntimeFailure = lensoContractRuntime.RuntimeFailure;
export type UnknownDomainError = lensoContractRuntime.UnknownDomainError;
export type StreamEvent<Message, DomainError> = lensoContractRuntime.StreamEvent<Message, DomainError>;
export type StreamSession<Message, DomainError> = lensoContractRuntime.StreamSession<Message, DomainError>;

export type ProviderStream<Message, DomainError> = StreamSession<Message, DomainError> | AsyncIterable<Message>;

class ServerOutputStreamInputError extends Error {}

function isAsyncIterable<Message>(value: unknown): value is AsyncIterable<Message> {
  return typeof value === "object" && value !== null && Symbol.asyncIterator in value;
}

function lowerProviderStream<Message, DomainError>(stream: ProviderStream<Message, DomainError>): StreamSession<Message, DomainError> {
  if (!isAsyncIterable<Message>(stream)) return stream;
  const iterator = stream[Symbol.asyncIterator]();
  let cancelled = false;
  return {
    async send() { throw new ServerOutputStreamInputError("server-output stream does not accept inbound messages"); },
    async receive() {
      if (cancelled) return { kind: "terminal", outcome: { ok: true } };
      const next = await iterator.next();
      return next.done
        ? { kind: "terminal", outcome: { ok: true } }
        : { kind: "message", message: next.value };
    },
    async closeSend() {},
    cancel() {
      cancelled = true;
      const closing = iterator.return?.();
      if (closing !== undefined) void Promise.resolve(closing).catch(() => undefined);
    },
  };
}

export interface CapabilityContractReference<Client, Provider extends object, Runtime extends DependencyInvoker = DependencyInvoker> extends CapabilityDependencyBinding<Client, Runtime> {
  readonly kind: "lenso.capability";
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly descriptor_digest: string;
  readonly generated_client: string;
  readonly descriptor: CapabilityProviderDescriptor;
  bindProvider(provider: Provider): CapabilityProviderBinding;
  required(id?: string): CapabilityDependencyDeclaration<Client, "one", Runtime>;
  optional(id?: string): CapabilityDependencyDeclaration<Client, "optional", Runtime>;
  many(id?: string): CapabilityDependencyDeclaration<Client, "many", Runtime>;
  readonly __client?: Client;
  readonly __provider?: Provider;
}

export interface CatalogRequest {

}

export interface CatalogResponse {
  commands: Array<CommandDefinition>;
}

export interface CommandDefinition {
  description: string;
  id: string;
  output_formats: Array<"text" | "json">;
  parameters: Array<CommandParameter>;
  path: Array<string>;
  summary: string;
}

export interface CommandParameter {
  choices: Array<string>;
  description: string;
  id: string;
  kind: "positional" | "option" | "flag";
  long?: string | null;
  multiple: boolean;
  required: boolean;
  short?: string | null;
  value_name?: string | null;
}

export interface ExecuteOpen {
  arguments_json: string;
  id: string;
  output_format: "text" | "json";
}

export interface ExecuteMessage {
  content: string;
  content_type: "text" | "json";
  kind: "stdout" | "stderr" | "progress" | "result";
}

export interface ExecutionFailedPayload {
  details_json: string;
  message: string;
  reason_code: string;
}

export type CatalogError = "catalog_invalid" | UnknownDomainError;
export type CatalogInvocationError = { readonly kind: "domain"; readonly error: CatalogError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type CatalogResult = { readonly ok: true; readonly value: CatalogResponse } | { readonly ok: false; readonly error: CatalogInvocationError };
export type ExecuteError = { readonly code: "execution_failed"; readonly payload: ExecutionFailedPayload } | "invalid_arguments" | "not_found" | "output_limit_exceeded" | "permission_denied" | UnknownDomainError;
export type ExecuteInvocationError = { readonly kind: "domain"; readonly error: ExecuteError } | { readonly kind: "runtime"; readonly error: RuntimeFailure };
export type ExecuteResult = { readonly ok: true; readonly value: StreamSession<ExecuteMessage, ExecuteError> } | { readonly ok: false; readonly error: ExecuteInvocationError };
export type ExecuteProviderResult = { readonly ok: true; readonly value: ProviderStream<ExecuteMessage, ExecuteError> } | { readonly ok: false; readonly error: ExecuteInvocationError };
export type ExecuteProviderOutput = AsyncIterable<ExecuteMessage> | ExecuteProviderResult | Promise<ExecuteProviderResult>;
export function encodeCatalogRequest(value: CatalogRequest): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeCatalogRequest(wire: string): CatalogRequest { return lensoContractRuntime.decodePortableJson<CatalogRequest>(wire); }
export function encodeCatalogResponse(value: CatalogResponse): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeCatalogResponse(wire: string): CatalogResponse { return lensoContractRuntime.decodePortableJson<CatalogResponse>(wire); }
export function encodeCatalogError(value: CatalogError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeCatalogError(wire: string): CatalogError { return lensoContractRuntime.decodeDomainError<CatalogError>(wire, ["catalog_invalid"]); }

export function encodeExecuteRequest(value: ExecuteOpen): string { return lensoContractRuntime.encodePortableJson(value, "request"); }
export function decodeExecuteRequest(wire: string): ExecuteOpen { return lensoContractRuntime.decodePortableJson<ExecuteOpen>(wire); }
export function encodeExecuteResponse(value: ExecuteMessage): string { return lensoContractRuntime.encodePortableJson(value, "response"); }
export function decodeExecuteResponse(wire: string): ExecuteMessage { return lensoContractRuntime.decodePortableJson<ExecuteMessage>(wire); }
export function encodeExecuteError(value: ExecuteError): string { return lensoContractRuntime.encodePortableJson(value, "Domain Error"); }
export function decodeExecuteError(wire: string): ExecuteError { return lensoContractRuntime.decodeDomainError<ExecuteError>(wire, ["invalid_arguments", "not_found", "output_limit_exceeded", "permission_denied"]); }


export interface CommandProviderClient {
  catalog(request: CatalogRequest, context?: InvocationContext): Promise<CatalogResult>;
  execute(request: ExecuteOpen, context?: InvocationContext): Promise<ExecuteResult>;
}

export interface CommandProviderProvider {
  catalog(context: InvocationContext, request: CatalogRequest): Promise<CatalogResult>;
  execute(context: InvocationContext, request: ExecuteOpen): ExecuteProviderOutput;
}

export const CommandProvider: CapabilityContractReference<CommandProviderClient, CommandProviderProvider, InteractionDependencyInvoker> = { kind: "lenso.capability", ...bindCommandProviderDependency(), capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, descriptor_digest: DESCRIPTOR_DIGEST, generated_client: "CommandProviderClient", descriptor: { capability_id: CAPABILITY_ID, descriptor_version: DESCRIPTOR_VERSION, operations: ["catalog", "execute"], stream_operations: ["execute"], event_operations: [] }, bindProvider: bindCommandProviderProvider, required(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "one" }; }, optional(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "optional" }; }, many(id) { return { kind: "lenso.dependency", ...(id === undefined ? {} : { id }), contract: this, cardinality: "many" }; }, };
export const COMMAND_PROVIDER_CONTRACT = CommandProvider;

export type ProviderDispatchOutcome =
  | { readonly kind: "success"; readonly value: unknown }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamActionOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderStreamReceiveOutcome =
  | { readonly kind: "message"; readonly value: unknown }
  | { readonly kind: "peer_half_closed" }
  | { readonly kind: "terminal_success" }
  | { readonly kind: "terminal_domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
/** @internal Runtime lowering seam. */
export interface ProviderStreamSessionBinding {
  send(message: unknown): Promise<ProviderStreamActionOutcome>;
  receive(): Promise<ProviderStreamReceiveOutcome>;
  closeSend(): Promise<ProviderStreamActionOutcome>;
  cancel(): void;
}
export type ProviderStreamOpenOutcome =
  | { readonly kind: "opened"; readonly stream: ProviderStreamSessionBinding }
  | { readonly kind: "domain"; readonly value: unknown }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };
export type ProviderEventPublishOutcome =
  | { readonly kind: "accepted" }
  | { readonly kind: "runtime"; readonly failure: RuntimeFailure };

export interface CapabilityProviderDescriptor {
  readonly capability_id: string;
  readonly descriptor_version: string;
  readonly operations: ReadonlyArray<string>;
  readonly stream_operations: ReadonlyArray<string>;
  readonly event_operations: ReadonlyArray<string>;
}

/** @internal Runtime lowering seam. */
export interface CapabilityProviderBinding {
  readonly descriptor: CapabilityProviderDescriptor;
  invokeRequest(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderDispatchOutcome>;
  openStream(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderStreamOpenOutcome>;
  publishEvent(
    operation: string,
    context: InvocationContext,
    payload: unknown,
  ): Promise<ProviderEventPublishOutcome>;
}

function providerErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

export function bindCommandProviderProvider(
  provider: CommandProviderProvider,
): CapabilityProviderBinding {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["catalog", "execute"],
      stream_operations: ["execute"],
      event_operations: [],
    },
    async invokeRequest(operation, context, payload) {
      switch (operation) {
      case "catalog": {
        let request: CatalogRequest;
        try {
          request = decodeCatalogRequest(lensoContractRuntime.encodePortableJson(payload, "request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const result = await provider.catalog(context, request);
          if (result.ok) {
            return { kind: "success", value: JSON.parse(encodeCatalogResponse(result.value)) as unknown };
          }
          if (result.error.kind === "domain") {
            return { kind: "domain", value: JSON.parse(encodeCatalogError(result.error.error)) as unknown };
          }
          return { kind: "runtime", failure: result.error.error };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async openStream(operation, context, payload) {
      switch (operation) {
      case "execute": {
        let request: ExecuteOpen;
        try {
          request = decodeExecuteRequest(lensoContractRuntime.encodePortableJson(payload, "stream open request"));
        } catch (error) {
          return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
        }
        try {
          const provided = provider.execute(context, request);
          const result = isAsyncIterable<ExecuteMessage>(provided)
            ? { ok: true as const, value: provided }
            : await provided;
          if (!result.ok) {
            if (result.error.kind === "domain") {
              return { kind: "domain", value: JSON.parse(encodeExecuteError(result.error.error)) as unknown };
            }
            return { kind: "runtime", failure: result.error.error };
          }
          const stream = lowerProviderStream(result.value);
          const binding: ProviderStreamSessionBinding = {
            async send(message) {
              let decoded: ExecuteMessage;
              try {
                decoded = decodeExecuteResponse(lensoContractRuntime.encodePortableJson(message, "stream message"));
              } catch (error) {
                return { kind: "runtime", failure: { kind: "protocol_violation", detail: providerErrorMessage(error) } };
              }
              try {
                await stream.send(decoded);
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: error instanceof ServerOutputStreamInputError
                  ? { kind: "protocol_violation", detail: providerErrorMessage(error) }
                  : { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async receive() {
              try {
                const event = await stream.receive();
                if (event.kind === "message") {
                  return { kind: "message", value: JSON.parse(encodeExecuteResponse(event.message)) as unknown };
                }
                if (event.kind === "peer_half_closed") return { kind: "peer_half_closed" };
                if (event.outcome.ok) return { kind: "terminal_success" };
                return { kind: "terminal_domain", value: JSON.parse(encodeExecuteError(event.outcome.error)) as unknown };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            async closeSend() {
              try {
                await stream.closeSend();
                return { kind: "accepted" };
              } catch (error) {
                return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
              }
            },
            cancel() { stream.cancel(); },
          };
          return { kind: "opened", stream: binding };
        } catch (error) {
          return { kind: "runtime", failure: { kind: "plugin_failure", detail: providerErrorMessage(error) } };
        }
      }
        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
    async publishEvent(operation, context, payload) {
      switch (operation) {

        default:
          return { kind: "runtime", failure: { kind: "unknown_operation", operation } };
      }
    },
  };
}

export type Provider = CommandProviderProvider;
export const bindProvider = bindCommandProviderProvider;

export type DependencyInvoker = (
  operation: string,
  context: InvocationContext,
  payload: unknown,
) => Promise<ProviderDispatchOutcome>;

export type InteractionDependencyInvoker = DependencyInvoker & {
  readonly providerInstance: string;
  openStream(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderStreamOpenOutcome>;
  publishEvent(operation: string, context: InvocationContext, payload: unknown): Promise<ProviderEventPublishOutcome>;
};

export interface CapabilityDependencyBinding<Client, Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly descriptor: CapabilityProviderDescriptor;
  createClient(invoke: Runtime): Client;
}

export interface CapabilityDependencyDeclaration<Client, Cardinality extends "one" | "optional" | "many", Runtime extends DependencyInvoker = DependencyInvoker> {
  readonly kind: "lenso.dependency";
  readonly id?: string;
  readonly contract: CapabilityDependencyBinding<Client, Runtime>;
  readonly cardinality: Cardinality;
}

function dependencyErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function dependencyRuntimeError(failure: RuntimeFailure): Error {
  return Object.assign(new Error(`Capability dependency failed: ${failure.kind}`), { failure });
}

function dependencyFailure(error: unknown): RuntimeFailure {
  if (typeof error === "object" && error !== null && "failure" in error) return (error as { failure: RuntimeFailure }).failure;
  return { kind: "plugin_failure", detail: dependencyErrorMessage(error) };
}

export function bindCommandProviderDependency(): CapabilityDependencyBinding<CommandProviderClient, InteractionDependencyInvoker> {
  return {
    descriptor: {
      capability_id: CAPABILITY_ID,
      descriptor_version: DESCRIPTOR_VERSION,
      operations: ["catalog", "execute"],
      stream_operations: ["execute"],
      event_operations: [],
    },
    createClient(invoke) {
      return {
      async catalog(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeCatalogRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke("catalog", call, payload);
          if (outcome.kind === "success") {
            return { ok: true, value: decodeCatalogResponse(JSON.stringify(outcome.value)) };
          }
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeCatalogError(JSON.stringify(outcome.value)) } };
          }
          return { ok: false, error: { kind: "runtime", error: outcome.failure } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "plugin_failure", detail: dependencyErrorMessage(error) } } };
        }
      },
      async execute(request, context) {
        let payload: unknown;
        try {
          payload = JSON.parse(encodeExecuteRequest(request)) as unknown;
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: { kind: "protocol_violation", detail: dependencyErrorMessage(error) } } };
        }
        const call = context ?? { requestId: "0" as Uint64, cancelled: false };
        try {
          const outcome = await invoke.openStream("execute", call, payload);
          if (outcome.kind === "domain") {
            return { ok: false, error: { kind: "domain", error: decodeExecuteError(JSON.stringify(outcome.value)) } };
          }
          if (outcome.kind === "runtime") {
            return { ok: false, error: { kind: "runtime", error: outcome.failure } };
          }
          const stream = outcome.stream;
          return { ok: true, value: {
            async send(message) {
              const encoded = JSON.parse(encodeExecuteResponse(message)) as unknown;
              const result = await stream.send(encoded);
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            async receive() {
              const result = await stream.receive();
              if (result.kind === "message") return { kind: "message", message: decodeExecuteResponse(JSON.stringify(result.value)) };
              if (result.kind === "peer_half_closed") return { kind: "peer_half_closed" };
              if (result.kind === "terminal_success") return { kind: "terminal", outcome: { ok: true } };
              if (result.kind === "terminal_domain") return { kind: "terminal", outcome: { ok: false, error: decodeExecuteError(JSON.stringify(result.value)) } };
              throw dependencyRuntimeError(result.failure);
            },
            async closeSend() {
              const result = await stream.closeSend();
              if (result.kind === "runtime") throw dependencyRuntimeError(result.failure);
            },
            cancel() { stream.cancel(); },
          } };
        } catch (error) {
          return { ok: false, error: { kind: "runtime", error: dependencyFailure(error) } };
        }
      },
      };
    },
  };
}

export const bindDependency = bindCommandProviderDependency;

export const portableValueProfile = lensoContractRuntime.portableValueProfile;
